services:
  xitter-frontend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  xitter-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4200:4200
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
           - node_modules/
